services:
  nginx:
    build:
      context: ./config/nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/src
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params.conf
      - ./logs:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - dockerpress-network

  php:
    build:
      context: ./config/php
      args:
        DEBIAN_MIRROR_DOMAIN: deb.debian.org
        PHP_EXTENSIONS: "${PHP_EXTENSIONS:-pdo_mysql mysqli gd curl opcache sockets redis imagick intl zip bcmath exif}"
        TZ: "${TZ:-UTC}"
    volumes:
      - ./src:/src
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs:/var/log/php
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    networks:
      - dockerpress-network

  mysql:
    image: mysql:8.0.36
    expose:
      - "3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-data:/var/lib/mysql/
      - ./logs:/var/log/mysql/
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-12345678}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST:-%}"
      TZ: "${TZ:-UTC}"
    networks:
      - dockerpress-network

networks:
  dockerpress-network:
    driver: bridge
